name: FixLengshangBackdoor
author: balugaq
description: This is a plugin which aims to fix Lengshang RSC backdoor
main: com.balugaq.flb.implementation.FixLengshangBackdoor
website: https://github.com/balugaq/FixLengshangBackdoor
version: ${project.version}
api-version: 1.17
depend:
  - Slimefun
softdepend:
  - GuizhanPluginLib
  - RykenSlimefunCustomizer

